name: releaser

on:
  push:
    tags:
      - '*'

jobs:
  releaser:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Chekout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create zip file (aviutl)
      run: |
        cp *.md script_aviutl
        cp LICENSE script_aviutl
        zip -r -q -@ GrungeConverter_${{ github.ref_name }}_AviUtl.zip ./script_aviutl

    - name: Create zip file (aviutl2)
      run: |
        cp *.md script_aviutl2
        cp LICENSE script_aviutl2
        zip -r -q -@ GrungeConverter_${{ github.ref_name }}_AviUtl2.zip ./script_aviutl2

    - name: Create release note
      run: |
        count=0
        IFS=$'\n'
        while read line; do
          if [ ${count} = 0 ] && [[ ${line} =~ "Change Log" ]]; then
            count=1
          elif [ ${count} = 1 ] && [[ ${line} =~ "*v" ]]; then
            count=2
          elif [ ${count} = 2 ] && [[ ${line} =~ "*v" ]]; then
            break
          elif [ ${count} = 2 ]; then
            echo ${line} >> ReleaseNote.txt
          fi
        done < README.md

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: GrungeConverter_${{ github.ref_name }}
        files: |
          *_AviUtl.zip
          *_AviUtl2.zip
        body_path: ReleaseNote.txt